name: My Sonar Path
on:
  push:   
  workflow_dispatch:   

 
jobs:  
  
  sonar:   
    runs-on: windows-latest    
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      - name: Call Sonar      
        id: sonar  
        uses: ./.github/workflows/Sonar/
