name: My inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        default: monalisa
        options:
          - monalisa
          - cschleiden    
jobs:
  greet:
    runs-on: windows-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      - name: Send greeting
        run: echo "${{ github.event.inputs.name }}"
      - name: Call initialize parameters
        id: unittest  
        uses: ./
        with:
          platform: x64
      - name: Print parameters
        id: unittestparams
        run: |
          echo "${{steps.unittest.outputs.simCoreExtenSionUnitTestPath}}"
          echo "${{steps.unittest.outputs.crashManagementUnitTestPath}}"
          echo "${{steps.unittest.outputs.simulationWrapperUnitTestPath}}"
          echo "${{steps.unittest.outputs.installerName}}"
        shell: powershell
