name: My inputs

on:
  push:   
  workflow_dispatch:
    inputs:
      targetPlatform:
        type: choice
        description: Target platform
        default: x64
        options:
          - x64         
          - x86

 
env:
  configuration: Release
  targetPlatform: ${{github.event.inputs.targetPlatform == '' && 'x64' || github.event.inputs.targetPlatform }}
  
jobs:
  greet:
    runs-on: windows-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      - name: Send greeting
        run: |
          echo "${{ github.event.inputs.targetPlatform }}"
          echo "${{ env.targetPlatform }}"
      - name: Call initialize parameters
        id: unittest  
        uses: ./
        with:
          platform: ${{ env.targetPlatform }}
      - name: Print parameters
        id: unittestparams
        run: |
         echo "Configuration: ${{ env.configuration }}"
          echo "${{steps.unittest.outputs.simCoreExtenSionUnitTestPath}}"
          echo "${{steps.unittest.outputs.simCoreExtenSionSearchDir}}"
          echo "${{steps.unittest.outputs.crashManagementUnitTestPath}}"
          echo "${{steps.unittest.outputs.crashManagementSearchDir}}"
          echo "${{steps.unittest.outputs.simulationWrapperUnitTestPath}}"
          echo "${{steps.unittest.outputs.simulationWrapperSearchDir}}"
          echo "${{steps.unittest.outputs.installerName}}"
        shell: powershell
