name: My triggered workflow

on:
   workflow_run:
     workflows: ["My inputs"]
     types: [completed] #requested

jobs:
  on-success:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "First workflow was a success"
      - name: Download artifact
        run: |
          gh run download -n my-artifact          
        env:
          GH_TOKEN: ${{ github.token }}
      

  on-failure:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
       - run: echo "First workflow was a failure"
