name: My triggered workflow

on:
   workflow_run:
     workflows: ["My inputs"]
     types: [completed] #requested

jobs:
  on-success:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "First workflow was a success"
      - name: Download artiact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
      

  on-failure:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
       - run: echo "First workflow was a failure"
